language: python
python:
    - "2.7.10"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
 nosetests -v --with-coverage
after_success:
  - coveralls
